import Topbar from "@/components/layout/topbar";
import Menu from "@/components/layout/footer-menu";
import { Trash2 } from "lucide-react";
import GenerateBillBtn from "@/components/ui/generate-bills";

export default function Bills() {
  return (
    <>
      <div className="lg:hidden">
        <Topbar />
      </div>

      <main className="pb-24 pt-5">
        <section className="z-50 px-3 lg:px-10">
          <div className="mb-4 flex flex-col gap-3 lg:flex-row">
            <div className="flex w-full items-center justify-between">
              <h1 className="flex items-center text-xl font-semibold lg:text-3xl">
                Bills
              </h1>

              <GenerateBillBtn />
            </div>
          </div>
        </section>

        <section className="grid grid-cols-2 justify-between gap-x-4 gap-y-8 px-3 md:grid-cols-3 lg:grid-cols-2 lg:p-10 xl:grid-cols-3">
          <BillCard />
          <BillCard />
          <BillCard />
        </section>
      </main>

      <Menu />
    </>
  );
}

function BillCard() {
  return (
    <article className="custom-shadow rounded-lg bg-white px-4 py-3 text-[14px]">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold">Peace Apartement Lakowe</h3>{" "}
        <p className="inline-block rounded-full bg-accent px-2 py-0.5 text-sm text-white">
          Paid
        </p>
      </div>
      <p className="font-medium">John Joshua</p>
      <p className="font-medium">18th September, 2024</p>
      <p className="mt-2 text-xl font-semibold">₦1000000</p>
      <div className="flex items-center justify-between">
        <div className="text-sm font-medium opacity-70">
          Generated By: Agent
        </div>
        <button className="flex h-8 w-8 items-center justify-center rounded-full bg-gray-200">
          <Trash2 size={14} />
        </button>
      </div>
    </article>
  );
}
